version: 0.0.{build}

init:
  - ps: if (Test-Path env:APPVEYOR_REPO_TAG) { $env:version = $env:APPVEYOR_REPO_TAG_NAME }
  - ps: Update-AppveyorBuild -Version $env:version

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(version)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2019
configuration: Release
platform: Any CPU

before_build:
- nuget restore src\allure-nunit.sln

build:
  verbosity: minimal

test: off

artifacts:
- path: '**\NUnit.Allure*.nupkg'